	FROM ubuntu:bionic

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
 autoconf \
 automake \
 bsdmainutils \
 ccache \
 clang-format \
 clang \
 cmake \
 g++ \
 gcc \
 gdb \
 glibc-source \
 libc6-dbg \
 libclang-dev \
 ninja-build \
 libboost-all-dev 

